### ISSUE TITLE
Could not find include file <ulp_c.h>

### ISSUE THREAD

**Issue by SensorsIot** [jasonful/lcc#10]
I thought I installed everything according to your instructions on a Windows 10 machine. Unfortunately, I get this error message when I try to compile primes.c

D:\Dropbox\Arduino\lcc\ulpcc\examples>ulpcc primes.c

D:\Dropbox\Arduino\lcc\ulpcc\examples>lcc -I\components\soc\esp32\include -I\components\soc\esp32\include\soc -I\inc -Wf-target=ulp -S primes.c -o primes.S
cpp: primes.c:2 Could not find include file <ulp_c.h>

ulp_c.h is in the \inc directory

**Comment by jasonful** [comment]
You do not have the ULPCCDIR environment variable set.  See the installation instructions in the README.

**Comment by SensorsIot** [comment]
I tried again to get it running. Unfortunately without success. Now I get the following error: 
C:\Users\andre\ulpcc\examples>lcc -IC:\Users\andre\esp\esp-idf\components\soc\esp32\include -IC:\Users\andre\esp\esp-idf\components\soc\esp32\include\soc -IC:\Users\andre\ulpcc\inc -Wf-target=ulp -S primes.c -o primes.S
cpp: C:\Users\andre\esp\esp-idf\components\soc\esp32\include\soc/soc.h:23 C:\Users\andre\esp\esp-idf\components\soc\esp32\include/soc/rtc_cntl_reg.h:21 C:\Users\andre\ulpcc\inc/ulp_c.h:6 primes.c:2 Could not find include file <esp_bit_defs.h>
The ULPCCDIR variable is defined and the path contains the the ulpcc\bin and the \esp directory. The IDF compiles the blink sketch. So it seems it is installed.
