### ISSUE TITLE
Further Thoughts

### ISSUE THREAD

**Issue by duff2013** [jasonful/lcc#4]
Hi Jason,
So I've been looking over this for a few days and see a couple of issues that I would like to bring to the table while working on the the Mac build as of late and somewhat the linux build.

1. The license is restrictive for **[lcc](https://github.com/jasonful/lcc/blob/master/CPYRIGHT)**, from my reading that anyone that tries to sell a product that relies on any part of lcc is not allowed unless you have a license agreement with the lcc creators. Not deal breaker but really only good for academic, hobby or research without the agreement.
2. The [HOSTFILE](https://github.com/jasonful/lcc/blob/master/makefile.nt#L3) should be made etc/ulp.c not the host os compiling for the ulp (_ulp.c would have to be created_). I noticed when it ran the cpp preprocessor the [flags](https://github.com/jasonful/lcc/blob/master/etc/win32.c#L15) are windows or linux specific and have no effect on the generated ulp assembly.

**Comment by jasonful** [comment]
1. You're right.  I didn't write lcc, so I can't control the license.
2.  I think it is correct as is.  lcc is inherently a cross-compiler, and the target it is compiling for is specified on the lcc command line, for example  "-Wf-target=ulp" in [ulpcc.bat](https://github.com/jasonful/lcc/blob/master/ulpcc/bin/ulpcc.bat)
What problem are you trying to solve?
