### ISSUE TITLE
Inline Assembly

### ISSUE THREAD

**Issue by drandreas** [jasonful/lcc#6]
I've implemented a timer for measuring distances using an HC-04:
```
  while (READ_RTC_REG(RTC_GPIO_IN_REG, RTC_GPIO_IN_NEXT_S + 15, 1) != 0) {
    i++;
  }
```

This compiles into (56 Cylces):
```
L.9:
  move r2,entry.raw   #Cycles 2+4 = 6
  ld r2,r2,0          #Cycles 4+4 = 8
  move r3,entry.raw   #Cycles 2+4 = 6
  st r2,r3,0          #Cycles 4+4 = 8
  reg_rd 265,29,29    #Cycles 8+4 = 8
  move r0,r0          #Cycles 2+4 = 6
  jump L.10, eq       #Cycles 2+2 = 4
  add r2,r2,1         #Cycles 2+4 = 6
  jump L.9            #Cycles 2+2 = 4
L.10:
```

The above assembly can measure (assuming the speed of sound at 343m/s and the ULP Clock at 8MHz) with a precision of ~1mm.

I've optimized the code to 
```
  move r2,entry.raw   #Cycles 2+4 = 6
  ld r2,r2,0          #Cycles 4+4 = 8
L.9:
  reg_rd 265,29,29    #Cycles 8+4 = 8
  move r0,r0          #Cycles 2+4 = 6
  jump L.10, eq       #Cycles 2+2 = 4
  add r2,r2,1         #Cycles 2+4 = 6
  jump L.9            #Cycles 2+2 = 4
L.10:
  move r3,entry.raw   #Cycles 2+4 = 6
  st r2,r3,0          #Cycles 4+4 = 8
```

Almost doubling the precision. Is there any way to use inline assembly or "functions" so I don't have to write the entire code in assembly?

**Comment by jasonful** [comment]
lcc does not claim to be an optimizing compiler.  So, I just added support for "inline" assembly (although it's not quite inline).  Add `include (1);` to your C code and the generated assembly will have a `.include "1.S"` at that spot, so you can put your custom assembly code in the file named 1.S .

**Comment by drandreas** [comment]
Thank you very much. I'll give it in the next couple of days and report back.
