### ISSUE TITLE
Can we do bit Shift? like >> or << and also Or Operation |=?

### ISSUE THREAD

**Issue by khawajamechatronics** [jasonful/lcc#7]
Hi,

I am trying to interface HX711 with ESP32 ULP Processor. I need to read data and shift. I have implemented the logic but it seems data is not correct. Would like to confirm if these functions are supported by library?

Kind Regards

**Comment by jasonful** [comment]
Yes, those should both already work.  If they don't seem to be working, send me your .c file and I'll take a look.

**Comment by khawajamechatronics** [comment]
Hi 

Thanks for prompt response, it seems another issue, I have written it here. https://github.com/duff2013/ulptool/issues/56#issue-562848863

Can you guide me on this? Thanks

**Comment by jasonful** [comment]
Closed
